export const checkbox = [
  { name: "category", value: "all", label: "All" },
  { name: "category", value: "smartphones", label: "Smartphones" },
  { name: "category", value: "laptops", label: "Laptops" },
  { name: "category", value: "fragrances", label: "Fragrances" },
  { name: "category", value: "skincare", label: "Skincare" },
  { name: "category", value: "groceries", label: "Groceries" },
  { name: "category", value: "home-decoration", label: "Home-decoration" },
  { name: "category", value: "men's clothing", label: "Men's clothing" },
  { name: "category", value: "jewelery", label: "Jewelery" },
  { name: "category", value: "electronics", label: "Electronics" },
  { name: "category", value: "women's clothing", label: "Women's clothing" },
  { name: "category", value: "watch", label: "Watch" },
  { name: "category", value: "mens-shoes", label: "Mens-shoes" },
  { name: "category", value: "womens-shoes", label: "Womens-shoes" },
  { name: "category", value: "womens-watches", label: "Womens-watches" },
  { name: "category", value: "mens-watches", label: "Mens-watches" },
  { name: "category", value: "womens-bags", label: "Womens-bags" },
  { name: "category", value: "sunglasses", label: "Sunglasses" },
];
